apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: flux-system
spec:
  # replicas: {{ .Values.replica }}
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
     annotations:
       timestamp: "{{ now | date "20060102150405" }}"
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: SampleApp01.azurecr.io/testcicdrepo:18570
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
  strategy:
    type: Recreate
