apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: flux-system
  labels: 
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-namespace: flux-system
    meta.helm.sh/release-name: flux
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
