# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'M0086 (75078e35-6d4e-436c-af4a-56b7b23022c6)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t sampleapp01.azurecr.io/testcicdrepo:tag
      az acr login -n sampleapp01
      docker push sampleapp01.azurecr.io/testcicdrepo:tag

- script: cat deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'M0086 (75078e35-6d4e-436c-af4a-56b7b23022c6)'
    azureResourceGroup: 'reactapp'
    kubernetesCluster: 'aks-reactapp'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'M0086 (75078e35-6d4e-436c-af4a-56b7b23022c6)'
    azureContainerRegistry: 'sampleapp01.azurecr.io'
    forceUpdate: false




