trigger:
- main

resources:
- repo: self

variables:
  imageRepo: testcicdrepo
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: buildAndPush
        inputs:
          containerRegistry: 'testcicd'
          repository: 'testcicdrepo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          buildContext: '$(System.DefaultWorkingDirectory)'
          tags: |
            $(Build.BuildId)
            latest