trigger:
- main

resources:
- repo: self

variables:
  imageRepo: sampleapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testcicd'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(tag)
          latest
    
