# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: testcicd
    repository: testcicdrepo
    buildContext: '$(System.DefaultWorkingDirectory)'
    tags: |
     $(Build.BuildId)
     latest


- script: cat deploy.yaml

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aks-service-conn'
    namespace: 'default'
    manifests: 'deploy.yaml'
    






