apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aks-reactapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mycharts
      sourceRef:
        kind: GitRepository
        name: aks-reactapp
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: dev
  upgrade:
    crds: CreateReplace
