apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Helmpository
metadata:
  name: aks-reactapp
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/abhishekmotifworks/reactapp
  ref:
    branch: flux-cd
