apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aks-reactapp
  namespace: flux-ns
spec:
  chart:
    spec:
      chart: mycharts
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: aks-reactapp
  releaseName: testrelease
  interval: 1m0s
