apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aks-reactapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mycharts
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: aks-reactapp
  releaseName: aks-reactapp
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 1m0s
