apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: reactapp
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/abhishekmotifworks/reactapp.git
  ref:
    branch: main
